version: "3.1"
services:
  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=app
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - "3306:3306"

  redis:
    image: redis
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "6379:6379"

  app:
    build:
      args:
          - USER
          - UID
          - GID
      context: ./.docker/php-fpm/
      dockerfile: Dockerfile
    working_dir: /app
    links:
      - redis
      - db
    volumes:
      - .:/app
      - ./.docker/php-fpm/php.ini-development:/usr/local/etc/php/php.ini
      - ./.docker/php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf

  webserver:
    image: nginx:alpine
    working_dir: /app
    links:
      - app
    volumes:
      - .:/app
      - ./.docker/nginx/nginx_dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
